FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ARG VITE_QUESTION
ARG VITE_RESPONSE_TEXT
ARG VITE_RESPONSE_SUBTEXT
ARG VITE_RESPONSE_TYPE
ARG VITE_RESPONSE_VALUE
ARG VITE_YOUTUBE_URL

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html

# Expõe a porta 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]